trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    pip install -r requirements.txt
  displayName: Install dependencies

- script: |
    echo "Running basic check"
    python -c "import main"
  displayName: Test app import

- script: |
    docker build -t finbot-app .
  displayName: Build Docker Image