name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR (Docker)
      uses: docker/login-action@v3
      with:
        registry: finbotacr12345.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push with cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: finbotacr12345.azurecr.io/finbot-app:${{ github.sha }}
        cache-from: type=registry,ref=finbotacr12345.azurecr.io/finbot-app:cache
        cache-to: type=registry,ref=finbotacr12345.azurecr.io/finbot-app:cache,mode=max

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Set AKS context
      run: |
        az aks get-credentials --resource-group finbot-rg --name finbot-aks3 --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/finbot finbot=finbotacr12345.azurecr.io/finbot-app:${{ github.sha }}

